// Generated by CoffeeScript 1.6.3
(function() {
  var DoseSet, models;

  models = require('./models');

  DoseSet = models.DoseSet;

  exports.oneDoseSet = function(req, res) {
    return res.send('One DoseSet');
  };

  exports.findAll = function(req, res) {
    return DoseSet.find(function(err, doseSets) {
      return res.send(doseSets);
    });
  };

  exports.findById = function(req, res) {
    return DoseSet.findById(req.params.id, function(err, doseSet) {
      if (!err) {
        return res.send(doseSet);
      }
    });
  };

  exports.updateOne = function(req, res) {
    return DoseSet.findById(req.params.id, function(err, doseSet) {
      doseSet.title = req.body.title;
      doseSet.all = req.body.all;
      doseSet.favorited = req.body.favorited;
      return doseSet.save(function(err) {
        if (!err) {
          console.log("updated doseSet");
        }
        return res.send(doseSet);
      });
    });
  };

  exports.addOne = function(req, res) {
    var doseSet;
    doseSet = new DoseSet({
      title: req.body.title,
      all: req.body.all,
      favorited: req.body.favorited
    });
    return doseSet.save(function(err) {
      if (!err) {
        console.log("created doseSet");
      }
      return res.send(doseSet);
    });
  };

  exports.deleteOne = function(req, res) {
    return DoseSet.findById(req.params.id, function(err, doseSet) {
      return doseSet.remove(function(err) {
        if (!err) {
          console.log("removed doseSet");
          return res.send('');
        }
      });
    });
  };

}).call(this);
