// Generated by CoffeeScript 1.6.3
/*mongo = require 'mongodb'
dbhost = 'localhost'
dbport = mongo.Connection.DEFAULT_PORT
db = new mongo.Db 'MDD-Mongo', new mongo.Server dbhost, dbport, {}
#dosSetCollection = ''
db.open (error, db)->
	console.log 'Connected to mongo: ' + dbhost + ':' + dbport

#	db.collection 'doseSets', (error, collection)->
#		dosSetCollection = collection
*/


(function() {
  var Dose, DoseSet, mongoose, theport, uristring;

  mongoose = require('mongoose');

  uristring = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || 'mongodb://localhost/MDD_db';

  theport = process.env.PORT || 5000;

  mongoose.connect(uristring, function(err, res) {
    if (err) {
      return console.log('ERROR connecting to: ' + uristring + '. ' + err);
    } else {
      return console.log('Succeeded connected to: ' + uristring);
    }
  });

  DoseSet = mongoose.model('DoseSet', new mongoose.Schema({
    title: String,
    date: String,
    url: String,
    all: String,
    selected: String,
    tags: String,
    favorited: Boolean
  }));

  Dose = mongoose.model('Dose', new mongoose.Schema({
    comments_count: Number,
    created_at: String,
    did: Number,
    height: Number,
    image_400_url: String,
    image_teaser_url: String,
    image_url: String,
    likes_count: Number,
    player: Object,
    rebound_source_id: Number,
    rebounds_count: Number,
    short_url: String,
    title: String,
    url: String,
    views_count: Number,
    width: Number
  }));

}).call(this);
